/**
 * Difficulty presets for the chicken egg game
 * 응애(baby) → 동생(little sis) → 언니(big sis) → 엄마(mom)
 */
export const DIFFICULTIES = {
  baby: {
    label: '응애',
    emoji: '👶',
    color: '#81C784',
    tapsPerEgg: 2,
    targetEggs: 30,
    predatorSpawnBase: 20,
    predatorSpawnScale: 0.02,
    predatorSpeedMult: 0.5,
    predatorStealMult: 0.3,
    predatorMaxConcurrent: 1,
    goldenChanceBase: 0.25,
    goldenChanceComboBonus: 0.04,
    eggWaitTime: 5,
    eggGoldenWaitTime: 7,
    dogDuration: 20,
    dogChargeEggs: 8,
  },
  sister: {
    label: '동생',
    emoji: '🧒',
    color: '#4CAF50',
    tapsPerEgg: 3,
    targetEggs: 50,
    predatorSpawnBase: 15,
    predatorSpawnScale: 0.04,
    predatorSpeedMult: 0.7,
    predatorStealMult: 0.5,
    predatorMaxConcurrent: 2,
    goldenChanceBase: 0.18,
    goldenChanceComboBonus: 0.03,
    eggWaitTime: 4,
    eggGoldenWaitTime: 6,
    dogDuration: 15,
    dogChargeEggs: 10,
  },
  unni: {
    label: '언니',
    emoji: '👧',
    color: '#FF9800',
    tapsPerEgg: 4,
    targetEggs: 80,
    predatorSpawnBase: 12,
    predatorSpawnScale: 0.08,
    predatorSpeedMult: 1.0,
    predatorStealMult: 1.0,
    predatorMaxConcurrent: 3,
    goldenChanceBase: 0.12,
    goldenChanceComboBonus: 0.02,
    eggWaitTime: 3,
    eggGoldenWaitTime: 4,
    dogDuration: 10,
    dogChargeEggs: 15,
  },
  mom: {
    label: '엄마',
    emoji: '👩',
    color: '#E53935',
    tapsPerEgg: 5,
    targetEggs: 100,
    predatorSpawnBase: 8,
    predatorSpawnScale: 0.12,
    predatorSpeedMult: 1.5,
    predatorStealMult: 2.0,
    predatorMaxConcurrent: 4,
    goldenChanceBase: 0.06,
    goldenChanceComboBonus: 0.01,
    eggWaitTime: 2,
    eggGoldenWaitTime: 3,
    dogDuration: 6,
    dogChargeEggs: 20,
  },
};

export const DIFFICULTY_ORDER = ['baby', 'sister', 'unni', 'mom'];
