/**
 * Difficulty presets for the chicken egg game
 * 응애(baby) → 동생(little sis) → 언니(big sis) → 엄마(mom)
 */
export const DIFFICULTIES = {
  baby: {
    label: '응애',
    emoji: '👶',
    color: '#81C784',
    maxHp: 15,
    tapsPerEgg: 2,
    targetEggs: 50,
    predatorSpawnBase: 10,
    predatorSpawnScale: 0.05,
    predatorSpeedMult: 0.6,
    predatorStealMult: 0.5,
    predatorMaxConcurrent: 2,
    goldenChanceBase: 0.20,
    goldenChanceComboBonus: 0.03,
    eggWaitTime: 5,
    eggGoldenWaitTime: 7,
    dogDuration: 18,
    dogChargeEggs: 8,
  },
  sister: {
    label: '동생',
    emoji: '👧',
    color: '#4CAF50',
    maxHp: 12,
    tapsPerEgg: 2,
    targetEggs: 65,
    predatorSpawnBase: 8,
    predatorSpawnScale: 0.08,
    predatorSpeedMult: 0.9,
    predatorStealMult: 0.8,
    predatorMaxConcurrent: 3,
    predatorBurstChance: 0.1,
    goldenChanceBase: 0.15,
    goldenChanceComboBonus: 0.03,
    eggWaitTime: 4,
    eggGoldenWaitTime: 6,
    dogDuration: 14,
    dogChargeEggs: 10,
  },
  unni: {
    label: '언니',
    emoji: '💁‍♀️',
    color: '#FF9800',
    maxHp: 10,
    tapsPerEgg: 3,
    targetEggs: 80,
    predatorSpawnBase: 6,
    predatorSpawnScale: 0.08,
    predatorSpeedMult: 1.2,
    predatorStealMult: 1.4,
    predatorMaxConcurrent: 3,
    predatorMinInterval: 2.5,
    predatorTapsMult: 1.5,
    predatorBurstChance: 0.2,
    goldenChanceBase: 0.10,
    goldenChanceComboBonus: 0.02,
    eggWaitTime: 3,
    eggGoldenWaitTime: 4,
    dogDuration: 10,
    dogChargeEggs: 12,
  },
  mom: {
    label: '엄마',
    emoji: '👩',
    color: '#E53935',
    maxHp: 10,
    tapsPerEgg: 3,
    targetEggs: 100,
    predatorSpawnBase: 4,
    predatorSpawnScale: 0.04,
    predatorSpeedMult: 1.8,
    predatorStealMult: 2.5,
    predatorMaxConcurrent: 5,
    predatorMinInterval: 1.5,
    predatorTapsMult: 2,
    predatorStealDelay: 0.3,
    predatorBurstChance: 0.4,
    goldenChanceBase: 0.05,
    goldenChanceComboBonus: 0.01,
    eggWaitTime: 2,
    eggGoldenWaitTime: 3,
    dogDuration: 8,
    dogChargeEggs: 14,
  },
};

export const DIFFICULTY_ORDER = ['baby', 'sister', 'unni', 'mom'];
