/**
 * Difficulty presets for the chicken egg game
 * 응애(baby) → 동생(little sis) → 언니(big sis) → 엄마(mom)
 */
export const DIFFICULTIES = {
  baby: {
    label: '응애',
    emoji: '👶',
    color: '#81C784',
    maxHp: 20,
    tapsPerEgg: 2,
    targetEggs: 30,
    predatorSpawnBase: 14,
    predatorSpawnScale: 0.03,
    predatorSpeedMult: 0.5,
    predatorStealMult: 0.3,
    predatorMaxConcurrent: 1,
    goldenChanceBase: 0.25,
    goldenChanceComboBonus: 0.04,
    eggWaitTime: 5,
    eggGoldenWaitTime: 7,
    dogDuration: 20,
    dogChargeEggs: 8,
  },
  sister: {
    label: '동생',
    emoji: '👧',
    color: '#4CAF50',
    maxHp: 15,
    tapsPerEgg: 2,
    targetEggs: 40,
    predatorSpawnBase: 11,
    predatorSpawnScale: 0.06,
    predatorSpeedMult: 0.8,
    predatorStealMult: 0.6,
    predatorMaxConcurrent: 2,
    goldenChanceBase: 0.18,
    goldenChanceComboBonus: 0.03,
    eggWaitTime: 4,
    eggGoldenWaitTime: 6,
    dogDuration: 15,
    dogChargeEggs: 10,
  },
  unni: {
    label: '언니',
    emoji: '💁‍♀️',
    color: '#FF9800',
    maxHp: 12,
    tapsPerEgg: 3,
    targetEggs: 50,
    predatorSpawnBase: 9,
    predatorSpawnScale: 0.10,
    predatorSpeedMult: 1.1,
    predatorStealMult: 1.2,
    predatorMaxConcurrent: 3,
    predatorTapsMult: 1.5,
    goldenChanceBase: 0.12,
    goldenChanceComboBonus: 0.02,
    eggWaitTime: 3,
    eggGoldenWaitTime: 4,
    dogDuration: 10,
    dogChargeEggs: 12,
  },
  mom: {
    label: '엄마',
    emoji: '👩',
    color: '#E53935',
    maxHp: 8,
    tapsPerEgg: 3,
    targetEggs: 60,
    predatorSpawnBase: 5,
    predatorSpawnScale: 0.04,
    predatorSpeedMult: 1.8,
    predatorStealMult: 2.5,
    predatorMaxConcurrent: 5,
    predatorMinInterval: 1.5,
    predatorTapsMult: 2,
    predatorStealDelay: 0.4,
    predatorBurstChance: 0.4,
    goldenChanceBase: 0.06,
    goldenChanceComboBonus: 0.01,
    eggWaitTime: 2,
    eggGoldenWaitTime: 3,
    dogDuration: 10,
    dogChargeEggs: 12,
  },
};

export const DIFFICULTY_ORDER = ['baby', 'sister', 'unni', 'mom'];
